name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            client/node_modules
            server/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd client
          yarn install
          cd ../server
          yarn install

      - name: Build app
        run: |
          cd client
          echo "VITE_GRAPHQL_URI = https://backend.adnansh.in/graphql" > .env
          yarn build
          cd ../server
          yarn build

      - name: Setup git in server
        run: |
          cd server
          sed -i 's/\/client_build/ /' .gitignore
          sed -i 's/\/dist/ /' .gitignore
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git init
          git add --all
          git commit -m "Update server codebase"

      - name: Setup git in client
        run: |
          cd client
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git init
          git add --all
          git commit -m "Update client codebase"

      - name: Push server code to server branch
        uses: ad-m/github-push-action@master
        with:
          branch: server
          directory: ./server
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

      - name: Push client code to client branch
        uses: ad-m/github-push-action@master
        with:
          branch: client
          directory: ./client
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: server

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: /
          local-dir: client_build/
