name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{secrets.PAT}}

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: |
          cd client
          yarn install
          cd ../server
          yarn install

      - name: Build app
        run: |
          cd client
          yarn build
          cd ../server
          yarn build

      - name: Edit .gitignore file
        run: |
          cd server
          sed 's/client_build/qqq/' .gitignore

      - name: Push server code to server branch
        run: |
          cd server
          git init
          git add .
          git commit -m "Updating server codebase"
          git remote add origin https://github.com/Adnan-S-Husain/portfolio.git
          git checkout -b server
          git push --force origin server

      - name: Push client code to client branch
        run: |
          cd client
          git init
          git add .
          git commit -m "Updating client codebase"
          git remote add origin https://github.com/Adnan-S-Husain/portfolio.git
          git checkout -b client
          git push --force origin client
