name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 19

    - name: Install dependencies
      run: |
        cd client
        npm ci
        cd ../server
        npm ci

    - name: Build app
      run: |
        cd client
        npm run build
        cd ../server
        npm run build

    - name: Push server code to server branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: server
        force: true
        directory: server
        
    - name: Push client code to client branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: client
        force: true
        directory: client
